# Oh My ZSH Internals
export ZSH="${HOME}/.oh-my-zsh"
export ZSH_THEME="codespaces"
plugins=(git)
source "${ZSH}/oh-my-zsh.sh"

# Oh My ZSH Options
export DISABLE_AUTO_UPDATE="true"
export DISABLE_UPDATE_PROMPT="true"

# Shell Options
export HISTFILE="${HOME}/.commandhistory/.zsh_history"
