FROM public.ecr.aws/ubuntu/ubuntu:20.04_stable

ARG CONTAINER_USERNAME

COPY devcontainer/src/root /root/

RUN bash /root/build.sh

USER ${CONTAINER_USERNAME}

VOLUME [ "/home/${CONTAINER_USERNAME}/workspace" ]
VOLUME [ "/home/${CONTAINER_USERNAME}/.commandhistory" ]
VOLUME [ "/home/${CONTAINER_USERNAME}/.docker" ]
VOLUME [ "/var/lib/docker" ]

ENTRYPOINT [ "/usr/local/share/docker-init.sh", "/usr/local/share/ssh-init.sh" ]
CMD [ "/usr/bin/sleep", "infinity" ]