---
name: "Build Image"

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ "amd64", "arm64" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: setup_qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Container
        id: build
        uses: docker/build-push-action@v2
        with:
          file: devcontainer/Containerfile
          context: .
          platforms: linux/${{ matrix.platform }}
          load: true
          tags: |
            devcontainer:latest
          build-args: |
            CONTAINER_USERNAME="devcontainer"

      - name: Scan Container
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: devcontainer:latest
          fail-build: true
          severity-cutoff: critical

